### ISSUE TITLE
Empty lines in the menu

### ISSUE THREAD

**Issue by Nikobalt** [dfaust/plasma-applet-places-widget#9]
Hello and thank you work your useful work.

When I open the Places Widget menu, I get for empty line in the bottom of the menu :
![Screenshot_20210118_154256](https://user-images.githubusercontent.com/77627672/104929403-1cf10c00-59a4-11eb-99f4-ea9649e4047a.png)

This happens under Kubuntu 20.04, it didn't with 18.04.
Also, the first time I installed Places Widget (from the kde "add components menu"), the problem didn't appear yet. After the next logout/login, these lines showed.
Checking/unchecking show devices/timelines/etc boxes doesn't change anything.

Any clue ?

**Comment by dfaust** [comment]
Can you please check the version number (right-click the applet -> settings -> about).
This should be fixed in version 1.4 (see #6).

**Comment by Nikobalt** [comment]
Oh sorry I didn't find this other thread while searching.

I can't find any _about_ menu :
![image](https://user-images.githubusercontent.com/77627672/105161330-8c383e80-5b11-11eb-8cff-ff44ca770ba1.png)

I just updated the widget via the widget download manager but the problem remains
